// frontend/src/views/LandingView.tsx
'use client'

import Link from 'next/link'
import { useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useAuthStore } from '@/store/authStore'

export default function LandingView() {
  const router = useRouter()
  const { accessToken, memberId } = useAuthStore()

  useEffect(() => {
    if (accessToken && memberId) {
      router.replace(`/members/${memberId}/today`)
    }
  }, [accessToken, memberId, router])

  return (
    <div className="page landing-page">
      <div className="topbar">
        <span className="topbar-brand">timemgr</span>
        <div className="topbar-actions" style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <Link href="/login" className="btn btn-ghost topbar-btn">Sign in</Link>
          <Link href="/register" className="btn btn-primary topbar-btn">Get started</Link>
        </div>
      </div>

      <div className="landing-body" style={{ display: 'flex', flexDirection: 'column', minHeight: 'calc(100vh - 52px)', paddingBottom: 60 }}>
        <div style={{ margin: '80px 0 48px' }}>
          <p className="mono" style={{ fontSize: 10, color: 'var(--accent)', letterSpacing: '0.2em', textTransform: 'uppercase', marginBottom: 24, display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{ display: 'inline-block', width: 24, height: 1, background: 'var(--accent)', opacity: 0.5 }} />
            time tracking
          </p>
          <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: 'clamp(42px, 7vw, 68px)', lineHeight: 1.08, color: 'var(--text)', marginBottom: 24, letterSpacing: '-0.01em' }}>
            Every second<br />accounted for.
          </h1>
          <p style={{ fontSize: 14, color: 'var(--text-2)', lineHeight: 1.8, fontWeight: 300, maxWidth: 340 }}>
            A focused workspace for tracking what matters.<br />
            Start, stop, and review your time with precision.
          </p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 24, marginBottom: 64, flexWrap: 'wrap' }}>
          <Link href="/register" className="btn btn-primary" style={{ height: 40, padding: '0 24px', fontSize: 13 }}>
            Get started — it's free
            <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
              <path d="M2.5 6.5h8M7 3l3.5 3.5L7 10" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </Link>
          <Link href="/login" className="mono" style={{ fontSize: 11, color: 'var(--text-2)', letterSpacing: '0.04em' }}>
            Already have an account? Sign in
          </Link>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', borderTop: '1px solid var(--border-subtle)', marginBottom: 'auto' }}>
          {[
            { title: 'Hierarchical tags', desc: 'Organize your work into nested tags. Track time at any level.' },
            { title: 'Precise stopwatch', desc: 'Session, daily, and lifetime totals — always up to date.' },
            { title: 'Full history', desc: 'Browse and edit every record. Nothing is lost.' },
          ].map(({ title, desc }) => (
            <div key={title} style={{ display: 'flex', alignItems: 'flex-start', gap: 20, padding: '24px 0', borderBottom: '1px solid var(--border-subtle)' }}>
              <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--accent)', flexShrink: 0, marginTop: 6 }} />
              <div>
                <p style={{ fontSize: 13, fontWeight: 500, marginBottom: 4 }}>{title}</p>
                <p style={{ fontSize: 12, color: 'var(--text-2)', lineHeight: 1.7 }}>{desc}</p>
              </div>
            </div>
          ))}
        </div>

        <footer style={{ marginTop: 40 }}>
          <span className="mono" style={{ fontSize: 10, color: 'var(--text-3)' }}>timemgr · v0.1</span>
        </footer>
      </div>
    </div>
  )
}

// frontend/src/views/LandingView.vue
<template>
  <div class="page landing-page">
    <div class="topbar">
      <span class="topbar-brand">timemgr</span>
      <div class="topbar-actions">
        <router-link to="/login" class="btn btn-ghost topbar-btn">Sign in</router-link>
        <router-link to="/register" class="btn btn-primary topbar-btn">Get started</router-link>
      </div>
    </div>

    <div class="landing-body">
      <div class="landing-hero">
        <p class="landing-eyebrow">time tracking</p>
        <h1 class="landing-title">Every second<br>accounted for.</h1>
        <p class="landing-desc">
          A focused workspace for tracking what matters.<br>
          Start, stop, and review your time with precision.
        </p>
      </div>

      <div class="landing-cta">
        <router-link to="/register" class="btn btn-primary landing-cta-btn">
          Get started — it's free
          <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
            <path d="M2.5 6.5h8M7 3l3.5 3.5L7 10" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </router-link>
        <router-link to="/login" class="landing-signin-link mono">
          Already have an account? Sign in
        </router-link>
      </div>

      <div class="landing-features">
        <div class="feature-item">
          <span class="feature-dot"></span>
          <div>
            <p class="feature-title">Hierarchical tags</p>
            <p class="feature-desc">Organize your work into nested tags. Track time at any level.</p>
          </div>
        </div>
        <div class="feature-item">
          <span class="feature-dot"></span>
          <div>
            <p class="feature-title">Precise stopwatch</p>
            <p class="feature-desc">Session, daily, and lifetime totals — always up to date.</p>
          </div>
        </div>
        <div class="feature-item">
          <span class="feature-dot"></span>
          <div>
            <p class="feature-title">Full history</p>
            <p class="feature-desc">Browse and edit every record. Nothing is lost.</p>
          </div>
        </div>
      </div>

      <footer class="landing-footer">
        <span class="mono">timemgr · v0.1</span>
      </footer>
    </div>
  </div>
</template>

<script setup>
import { onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '@/stores/authStore';

const router = useRouter();
const authStore = useAuthStore();

onMounted(() => {
  if (authStore.isAuthenticated && authStore.memberId) {
    router.replace(`/members/${authStore.memberId}/today`);
  }
});
</script>

<style scoped>
.landing-page { position: relative; }

.topbar-actions { display: flex; gap: 8px; align-items: center; }

.topbar-btn {
  height: 28px;
  padding: 0 12px;
  font-size: 11px;
  font-family: var(--font-mono);
  letter-spacing: 0.06em;
}

.landing-body {
  display: flex;
  flex-direction: column;
  min-height: calc(100vh - 52px);
  padding-bottom: 60px;
}

/* Hero */
.landing-hero { margin: 80px 0 48px; }

.landing-eyebrow {
  font-family: var(--font-mono);
  font-size: 10px;
  color: var(--accent);
  letter-spacing: 0.2em;
  text-transform: uppercase;
  margin-bottom: 24px;
  display: flex;
  align-items: center;
  gap: 10px;
}

.landing-eyebrow::before {
  content: '';
  display: inline-block;
  width: 24px;
  height: 1px;
  background: var(--accent);
  opacity: 0.5;
}

.landing-title {
  font-family: var(--font-serif);
  font-size: clamp(42px, 7vw, 68px);
  line-height: 1.08;
  color: var(--text);
  margin-bottom: 24px;
  letter-spacing: -0.01em;
}

.landing-desc {
  font-size: 14px;
  color: var(--text-2);
  line-height: 1.8;
  font-weight: 300;
  max-width: 340px;
}

/* CTA */
.landing-cta {
  display: flex;
  align-items: center;
  gap: 24px;
  margin-bottom: 64px;
  flex-wrap: wrap;
}

.landing-cta-btn {
  height: 40px;
  padding: 0 24px;
  font-size: 13px;
}

.landing-signin-link {
  font-size: 11px;
  color: var(--text-2);
  letter-spacing: 0.04em;
  transition: color var(--t);
}

.landing-signin-link:hover { color: var(--text); }

/* Features */
.landing-features {
  display: flex;
  flex-direction: column;
  gap: 0;
  border-top: 1px solid var(--border-subtle);
  margin-bottom: auto;
}

.feature-item {
  display: flex;
  align-items: flex-start;
  gap: 20px;
  padding: 24px 0;
  border-bottom: 1px solid var(--border-subtle);
}

.feature-dot {
  width: 5px;
  height: 5px;
  border-radius: 50%;
  background: var(--accent);
  opacity: 0.5;
  flex-shrink: 0;
  margin-top: 8px;
}

.feature-title {
  font-size: 13px;
  color: var(--text);
  margin-bottom: 4px;
  font-weight: 500;
}

.feature-desc {
  font-size: 12px;
  color: var(--text-2);
  line-height: 1.6;
}

/* Footer */
.landing-footer {
  padding-top: 48px;
  font-family: var(--font-mono);
  font-size: 10px;
  color: var(--text-3);
  letter-spacing: 0.1em;
}

.mono { font-family: var(--font-mono); }
</style>
