// frontend/src/views/LogsView.tsx
'use client'

import { useCallback, useEffect, useState } from 'react'
import AppShell from '@/components/layout/AppShell'
import TagPickerModal from '@/components/TagPickerModal'
import { useAuthStore } from '@/store/authStore'
import { useTagStore } from '@/store/tagStore'
import apiClient from '@/utils/apiClient'

// ────────────────────────────────────────────────────────────
// Types
// ────────────────────────────────────────────────────────────

interface SessionDetail {
  startTime: string
  endTime: string
  durationSeconds: number
}

interface TagSummary {
  tagId: number
  tagName: string
  parentTagName: string
  totalSeconds: number
  sessionCount: number
  sessions: SessionDetail[]
}

interface SummaryData {
  totalSeconds: number
  tagSummaries: TagSummary[]
}

// ────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────

function fmtDuration(s: number): string {
  const h = Math.floor(s / 3600)
  const m = Math.floor((s % 3600) / 60)
  if (h > 0) return `${h}h ${m}m`
  return `${m}m`
}

function fmtHMS(s: number): string {
  const h = String(Math.floor(s / 3600)).padStart(2, '0')
  const m = String(Math.floor((s % 3600) / 60)).padStart(2, '0')
  const sc = String(Math.floor(s % 60)).padStart(2, '0')
  return `${h}:${m}:${sc}`
}

function toLocalDate(d: Date): string {
  return d.toLocaleDateString('sv-SE') // YYYY-MM-DD
}

function startOfWeek(d: Date): Date {
  const day = d.getDay()
  const diff = (day === 0 ? -6 : 1 - day)
  const mon = new Date(d)
  mon.setDate(d.getDate() + diff)
  mon.setHours(0, 0, 0, 0)
  return mon
}

function addDays(d: Date, n: number): Date {
  const r = new Date(d)
  r.setDate(r.getDate() + n)
  return r
}

function startOfMonth(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), 1)
}

function endOfMonth(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth() + 1, 0)
}

function isSameDay(a: Date, b: Date): boolean {
  return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate()
}

function weekLabel(mon: Date): string {
  const sun = addDays(mon, 6)
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' }
  return `${mon.toLocaleDateString('en-US', opts)} – ${sun.toLocaleDateString('en-US', opts)}`
}

// ────────────────────────────────────────────────────────────
// Summary bar
// ────────────────────────────────────────────────────────────

function TagBar({ summary, total }: { summary: TagSummary; total: number }) {
  const pct = total > 0 ? (summary.totalSeconds / total) * 100 : 0
  return (
    <div style={{ marginBottom: 12 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 4 }}>
        <div style={{ display: 'flex', gap: 6, alignItems: 'baseline' }}>
          {summary.parentTagName && (
            <span className="mono" style={{ fontSize: 10, color: 'var(--text-3)' }}>{summary.parentTagName} /</span>
          )}
          <span style={{ fontSize: 13 }}>{summary.tagName}</span>
          <span className="mono" style={{ fontSize: 10, color: 'var(--text-3)' }}>{summary.sessionCount}세션</span>
        </div>
        <span className="mono" style={{ fontSize: 12 }}>{fmtHMS(summary.totalSeconds)}</span>
      </div>
      <div style={{ height: 4, background: 'var(--border-subtle)', borderRadius: 2, overflow: 'hidden' }}>
        <div style={{ width: `${pct}%`, height: '100%', background: 'var(--accent)', borderRadius: 2, transition: 'width 0.3s' }} />
      </div>
    </div>
  )
}

// ────────────────────────────────────────────────────────────
// Navigation controls
// ────────────────────────────────────────────────────────────

function NavArrows({ label, onPrev, onNext }: { label: string; onPrev: () => void; onNext: () => void }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24 }}>
      <button onClick={onPrev} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-2)', display: 'flex' }}>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M10 3L5 8l5 5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/></svg>
      </button>
      <span className="mono" style={{ fontSize: 12, color: 'var(--text)', minWidth: 160, textAlign: 'center' }}>{label}</span>
      <button onClick={onNext} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-2)', display: 'flex' }}>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M6 3l5 5-5 5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/></svg>
      </button>
    </div>
  )
}

// ────────────────────────────────────────────────────────────
// Daily tab
// ────────────────────────────────────────────────────────────

function DailyTab({ memberId }: { memberId: number }) {
  const [date, setDate] = useState(new Date())
  const [data, setData] = useState<SummaryData | null>(null)
  const [loading, setLoading] = useState(false)

  const fetch = useCallback(async (d: Date) => {
    setLoading(true)
    const ds = toLocalDate(d)
    try {
      const res = await apiClient.get<SummaryData>(`/api/v1/records/summary?startDate=${ds}&endDate=${ds}`)
      setData(res.data)
    } catch { setData(null) }
    finally { setLoading(false) }
  }, [])

  useEffect(() => { fetch(date) }, [date, fetch])

  const label = date.toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'short' })

  return (
    <div>
      <NavArrows
        label={label}
        onPrev={() => setDate((d) => addDays(d, -1))}
        onNext={() => setDate((d) => addDays(d, 1))}
      />
      {loading && <div className="spinner" style={{ margin: '40px auto' }} />}
      {!loading && data && (
        <>
          <div style={{ textAlign: 'center', marginBottom: 32 }}>
            <div className="mono" style={{ fontSize: 'clamp(28px, 8vw, 44px)', color: 'var(--text)', letterSpacing: '-0.02em' }}>
              {fmtHMS(data.totalSeconds)}
            </div>
            <span className="mono" style={{ fontSize: 10, color: 'var(--text-3)', letterSpacing: '0.15em', textTransform: 'uppercase' }}>total</span>
          </div>
          {data.tagSummaries.length === 0 && (
            <p style={{ fontSize: 13, color: 'var(--text-3)', textAlign: 'center' }}>기록이 없습니다</p>
          )}
          {data.tagSummaries.map((t) => (
            <TagBar key={t.tagId} summary={t} total={data.totalSeconds} />
          ))}
          {/* Session timeline */}
          {data.tagSummaries.some((t) => t.sessions.length > 0) && (
            <div style={{ marginTop: 24 }}>
              <p className="mono" style={{ fontSize: 9, color: 'var(--text-3)', letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: 12 }}>sessions</p>
              {data.tagSummaries.flatMap((t) =>
                t.sessions.map((s, i) => (
                  <div key={`${t.tagId}-${i}`} style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid var(--border-subtle)' }}>
                    <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                      <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--text-3)', flexShrink: 0 }} />
                      <span style={{ fontSize: 12 }}>{t.tagName}</span>
                    </div>
                    <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                      <span className="mono" style={{ fontSize: 11, color: 'var(--text-3)' }}>
                        {new Date(s.startTime).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' })}
                        {' → '}
                        {new Date(s.endTime).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' })}
                      </span>
                      <span className="mono" style={{ fontSize: 11, color: 'var(--text)' }}>{fmtDuration(s.durationSeconds)}</span>
                    </div>
                  </div>
                ))
              )}
            </div>
          )}
        </>
      )}
      {!loading && !data && <p className="mono" style={{ fontSize: 11, color: 'var(--danger)' }}>불러오지 못했습니다.</p>}
    </div>
  )
}

// ────────────────────────────────────────────────────────────
// Weekly tab
// ────────────────────────────────────────────────────────────

function WeeklyTab({ memberId }: { memberId: number }) {
  const [monday, setMonday] = useState(() => startOfWeek(new Date()))
  const [data, setData] = useState<SummaryData | null>(null)
  const [loading, setLoading] = useState(false)

  const fetchWeek = useCallback(async (mon: Date) => {
    setLoading(true)
    const sun = addDays(mon, 6)
    try {
      const res = await apiClient.get<SummaryData>(`/api/v1/records/summary?startDate=${toLocalDate(mon)}&endDate=${toLocalDate(sun)}`)
      setData(res.data)
    } catch { setData(null) }
    finally { setLoading(false) }
  }, [])

  useEffect(() => { fetchWeek(monday) }, [monday, fetchWeek])

  // Fetch per-day data for bar chart
  const [dailyTotals, setDailyTotals] = useState<number[]>([])
  useEffect(() => {
    const days = Array.from({ length: 7 }, (_, i) => addDays(monday, i))
    Promise.all(
      days.map((d) =>
        apiClient
          .get<SummaryData>(`/api/v1/records/summary?startDate=${toLocalDate(d)}&endDate=${toLocalDate(d)}`)
          .then((r) => r.data.totalSeconds)
          .catch(() => 0)
      )
    ).then(setDailyTotals)
  }, [monday])

  const maxDay = Math.max(...dailyTotals, 1)
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  const today = new Date()

  return (
    <div>
      <NavArrows
        label={weekLabel(monday)}
        onPrev={() => setMonday((d) => addDays(d, -7))}
        onNext={() => setMonday((d) => addDays(d, 7))}
      />
      {/* 7-day bar chart */}
      <div style={{ display: 'flex', gap: 6, alignItems: 'flex-end', height: 80, marginBottom: 24 }}>
        {days.map((dayLabel, i) => {
          const dayDate = addDays(monday, i)
          const secs = dailyTotals[i] ?? 0
          const isToday = isSameDay(dayDate, today)
          return (
            <div key={i} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 }}>
              <div style={{ width: '100%', display: 'flex', alignItems: 'flex-end', height: 60 }}>
                <div style={{ width: '100%', height: `${(secs / maxDay) * 100}%`, minHeight: secs > 0 ? 3 : 0, background: isToday ? 'var(--accent)' : 'var(--border)', borderRadius: 2, transition: 'height 0.3s' }} />
              </div>
              <span className="mono" style={{ fontSize: 9, color: isToday ? 'var(--accent)' : 'var(--text-3)' }}>{dayLabel}</span>
            </div>
          )
        })}
      </div>

      {loading && <div className="spinner" style={{ margin: '20px auto' }} />}
      {!loading && data && (
        <>
          <div style={{ display: 'flex', gap: 16, marginBottom: 24 }}>
            <div style={{ flex: 1, background: 'var(--surface-2)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius)', padding: '14px 16px', textAlign: 'center' }}>
              <p className="mono" style={{ fontSize: 9, color: 'var(--text-3)', letterSpacing: '0.1em', marginBottom: 6 }}>WEEK TOTAL</p>
              <p className="mono" style={{ fontSize: 16 }}>{fmtHMS(data.totalSeconds)}</p>
            </div>
            <div style={{ flex: 1, background: 'var(--surface-2)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius)', padding: '14px 16px', textAlign: 'center' }}>
              <p className="mono" style={{ fontSize: 9, color: 'var(--text-3)', letterSpacing: '0.1em', marginBottom: 6 }}>DAILY AVG</p>
              <p className="mono" style={{ fontSize: 16 }}>{fmtHMS(Math.round(data.totalSeconds / 7))}</p>
            </div>
          </div>
          {data.tagSummaries.map((t) => (
            <TagBar key={t.tagId} summary={t} total={data.totalSeconds} />
          ))}
        </>
      )}
    </div>
  )
}

// ────────────────────────────────────────────────────────────
// Monthly tab
// ────────────────────────────────────────────────────────────

function MonthlyTab({ memberId }: { memberId: number }) {
  const [refDate, setRefDate] = useState(new Date())
  const [data, setData] = useState<SummaryData | null>(null)
  const [loading, setLoading] = useState(false)
  const [dailyTotals, setDailyTotals] = useState<Map<string, number>>(new Map())

  const fetchMonth = useCallback(async (d: Date) => {
    setLoading(true)
    const start = startOfMonth(d)
    const end = endOfMonth(d)
    try {
      const res = await apiClient.get<SummaryData>(`/api/v1/records/summary?startDate=${toLocalDate(start)}&endDate=${toLocalDate(end)}`)
      setData(res.data)
    } catch { setData(null) }
    finally { setLoading(false) }
  }, [])

  useEffect(() => { fetchMonth(refDate) }, [refDate, fetchMonth])

  // Per-day totals for heatmap (batch: one call per day is expensive, so we use per-week calls)
  useEffect(() => {
    const start = startOfMonth(refDate)
    const end = endOfMonth(refDate)
    const weeks: Date[] = []
    let cur = startOfWeek(start)
    while (cur <= end) {
      weeks.push(new Date(cur))
      cur = addDays(cur, 7)
    }
    Promise.all(
      weeks.map((mon) => {
        const sun = addDays(mon, 6)
        return apiClient
          .get<SummaryData>(`/api/v1/records/summary?startDate=${toLocalDate(mon)}&endDate=${toLocalDate(sun)}`)
          .then((r) => {
            // We only have week total — approximate by distributing across sessions
            const map = new Map<string, number>()
            r.data.tagSummaries.forEach((t) => {
              t.sessions.forEach((s) => {
                const key = toLocalDate(new Date(s.startTime))
                map.set(key, (map.get(key) ?? 0) + s.durationSeconds)
              })
            })
            return map
          })
          .catch(() => new Map<string, number>())
      })
    ).then((maps) => {
      const merged = new Map<string, number>()
      maps.forEach((m) => m.forEach((v, k) => merged.set(k, (merged.get(k) ?? 0) + v)))
      setDailyTotals(merged)
    })
  }, [refDate])

  const year = refDate.getFullYear()
  const month = refDate.getMonth()
  const monthLabel = refDate.toLocaleDateString('ko-KR', { year: 'numeric', month: 'long' })

  const firstDay = new Date(year, month, 1)
  const lastDay = new Date(year, month + 1, 0)
  const startPad = (firstDay.getDay() + 6) % 7
  const today = new Date()
  const maxVal = Math.max(...Array.from(dailyTotals.values()), 1)

  const cells: (Date | null)[] = [
    ...Array(startPad).fill(null),
    ...Array.from({ length: lastDay.getDate() }, (_, i) => new Date(year, month, i + 1)),
  ]

  const totalDays = data ? Math.round(data.totalSeconds / (lastDay.getDate() * 1)) : 0

  return (
    <div>
      <NavArrows
        label={monthLabel}
        onPrev={() => setRefDate((d) => new Date(d.getFullYear(), d.getMonth() - 1, 1))}
        onNext={() => setRefDate((d) => new Date(d.getFullYear(), d.getMonth() + 1, 1))}
      />

      {/* Heatmap calendar */}
      <div style={{ marginBottom: 24 }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 3, marginBottom: 4 }}>
          {['M','T','W','T','F','S','S'].map((d, i) => (
            <div key={i} className="mono" style={{ fontSize: 9, color: 'var(--text-3)', textAlign: 'center' }}>{d}</div>
          ))}
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 3 }}>
          {cells.map((d, i) => {
            if (!d) return <div key={i} />
            const key = toLocalDate(d)
            const secs = dailyTotals.get(key) ?? 0
            const intensity = secs / maxVal
            const isToday = isSameDay(d, today)
            return (
              <div
                key={i}
                title={`${d.getDate()}일: ${fmtDuration(secs)}`}
                style={{
                  aspectRatio: '1',
                  borderRadius: 3,
                  background: secs > 0
                    ? `rgba(var(--accent-rgb, 99,102,241), ${0.15 + intensity * 0.85})`
                    : 'var(--border-subtle)',
                  outline: isToday ? '2px solid var(--accent)' : undefined,
                  outlineOffset: 1,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <span className="mono" style={{ fontSize: 8, color: secs > 0 ? 'var(--bg)' : 'var(--text-3)', opacity: 0.8 }}>{d.getDate()}</span>
              </div>
            )
          })}
        </div>
      </div>

      {loading && <div className="spinner" style={{ margin: '20px auto' }} />}
      {!loading && data && (
        <>
          <div style={{ display: 'flex', gap: 16, marginBottom: 24 }}>
            <div style={{ flex: 1, background: 'var(--surface-2)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius)', padding: '14px 16px', textAlign: 'center' }}>
              <p className="mono" style={{ fontSize: 9, color: 'var(--text-3)', letterSpacing: '0.1em', marginBottom: 6 }}>MONTH TOTAL</p>
              <p className="mono" style={{ fontSize: 16 }}>{fmtHMS(data.totalSeconds)}</p>
            </div>
            <div style={{ flex: 1, background: 'var(--surface-2)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius)', padding: '14px 16px', textAlign: 'center' }}>
              <p className="mono" style={{ fontSize: 9, color: 'var(--text-3)', letterSpacing: '0.1em', marginBottom: 6 }}>DAILY AVG</p>
              <p className="mono" style={{ fontSize: 16 }}>{fmtHMS(Math.round(data.totalSeconds / lastDay.getDate()))}</p>
            </div>
          </div>
          {data.tagSummaries.map((t) => (
            <TagBar key={t.tagId} summary={t} total={data.totalSeconds} />
          ))}
        </>
      )}
    </div>
  )
}

// ────────────────────────────────────────────────────────────
// Tag tab
// ────────────────────────────────────────────────────────────

type TagPeriod = 'week' | 'month' | 'custom'

function TagTab({ memberId }: { memberId: number }) {
  const tagTree = useTagStore((s) => s.tagTree)
  const loadTags = useTagStore((s) => s.loadTags)
  const findById = useTagStore((s) => s.findById)

  const [showPicker, setShowPicker] = useState(false)
  const [selectedTagId, setSelectedTagId] = useState<number | null>(null)
  const [period, setPeriod] = useState<TagPeriod>('week')
  const [customStart, setCustomStart] = useState(() => toLocalDate(addDays(new Date(), -6)))
  const [customEnd, setCustomEnd] = useState(() => toLocalDate(new Date()))

  const [current, setCurrent] = useState<SummaryData | null>(null)
  const [prev, setPrev] = useState<SummaryData | null>(null)
  const [loading, setLoading] = useState(false)

  useEffect(() => { if (memberId) loadTags(memberId) }, [memberId, loadTags])

  function getRange(): [Date, Date] {
    const today = new Date()
    if (period === 'week') return [startOfWeek(today), addDays(startOfWeek(today), 6)]
    if (period === 'month') return [startOfMonth(today), endOfMonth(today)]
    return [new Date(customStart), new Date(customEnd)]
  }

  function getPrevRange(start: Date, end: Date): [Date, Date] {
    const len = Math.round((end.getTime() - start.getTime()) / 86400000) + 1
    return [addDays(start, -len), addDays(end, -len)]
  }

  useEffect(() => {
    if (!selectedTagId) return
    const [start, end] = getRange()
    const [pStart, pEnd] = getPrevRange(start, end)
    setLoading(true)
    Promise.all([
      apiClient.get<SummaryData>(`/api/v1/records/summary?startDate=${toLocalDate(start)}&endDate=${toLocalDate(end)}`),
      apiClient.get<SummaryData>(`/api/v1/records/summary?startDate=${toLocalDate(pStart)}&endDate=${toLocalDate(pEnd)}`),
    ])
      .then(([cur, pr]) => { setCurrent(cur.data); setPrev(pr.data) })
      .catch(() => { setCurrent(null); setPrev(null) })
      .finally(() => setLoading(false))
  }, [selectedTagId, period, customStart, customEnd])

  const selectedTag = selectedTagId ? findById(selectedTagId) : null

  function filterForTag(data: SummaryData): TagSummary[] {
    if (!selectedTagId) return []
    return data.tagSummaries.filter((t) => {
      if (t.tagId === selectedTagId) return true
      const tag = findById(t.tagId)
      if (!tag) return false
      // check if parent chain includes selectedTagId
      return t.parentTagName === selectedTag?.name
    })
  }

  const currentFiltered = current ? filterForTag(current) : []
  const prevFiltered = prev ? filterForTag(prev) : []
  const currentTotal = currentFiltered.reduce((s, t) => s + t.totalSeconds, 0)
  const prevTotal = prevFiltered.reduce((s, t) => s + t.totalSeconds, 0)
  const delta = prevTotal > 0 ? Math.round(((currentTotal - prevTotal) / prevTotal) * 100) : null

  return (
    <div>
      {/* Tag selector */}
      <button
        onClick={() => setShowPicker(true)}
        style={{ display: 'flex', alignItems: 'center', gap: 10, width: '100%', padding: '10px 14px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 'var(--radius)', cursor: 'pointer', color: 'var(--text)', marginBottom: 20 }}
      >
        <span style={{ width: 7, height: 7, borderRadius: '50%', background: 'var(--text-3)', flexShrink: 0 }} />
        <span style={{ flex: 1, textAlign: 'left', fontSize: 13 }}>{selectedTag?.name ?? '태그를 선택하세요'}</span>
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M3 4.5l3 3 3-3" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/></svg>
      </button>

      {/* Period selector */}
      <div style={{ display: 'flex', gap: 6, marginBottom: 20 }}>
        {(['week', 'month', 'custom'] as TagPeriod[]).map((p) => (
          <button
            key={p}
            onClick={() => setPeriod(p)}
            className="mono"
            style={{ padding: '5px 12px', background: period === p ? 'var(--accent)' : 'var(--surface-2)', border: `1px solid ${period === p ? 'var(--accent)' : 'var(--border)'}`, borderRadius: 'var(--radius)', color: period === p ? 'var(--bg)' : 'var(--text-2)', fontSize: 10, cursor: 'pointer', letterSpacing: '0.06em', textTransform: 'uppercase' }}
          >
            {p === 'week' ? '이번 주' : p === 'month' ? '이번 달' : '직접 입력'}
          </button>
        ))}
      </div>
      {period === 'custom' && (
        <div style={{ display: 'flex', gap: 8, marginBottom: 20, alignItems: 'center' }}>
          <input type="date" value={customStart} onChange={(e) => setCustomStart(e.target.value)} style={{ flex: 1, background: 'var(--input-bg)', border: '1px solid var(--border)', borderRadius: 'var(--radius)', padding: '6px 10px', color: 'var(--text)', fontSize: 12, fontFamily: 'inherit', outline: 'none' }} />
          <span className="mono" style={{ fontSize: 11, color: 'var(--text-3)' }}>~</span>
          <input type="date" value={customEnd} onChange={(e) => setCustomEnd(e.target.value)} style={{ flex: 1, background: 'var(--input-bg)', border: '1px solid var(--border)', borderRadius: 'var(--radius)', padding: '6px 10px', color: 'var(--text)', fontSize: 12, fontFamily: 'inherit', outline: 'none' }} />
        </div>
      )}

      {!selectedTagId && (
        <p style={{ fontSize: 13, color: 'var(--text-3)', textAlign: 'center', marginTop: 40 }}>태그를 선택하면 통계가 표시됩니다</p>
      )}

      {loading && <div className="spinner" style={{ margin: '40px auto' }} />}
      {!loading && selectedTagId && currentFiltered.length === 0 && (
        <p style={{ fontSize: 13, color: 'var(--text-3)', textAlign: 'center', marginTop: 40 }}>해당 기간에 기록이 없습니다</p>
      )}

      {!loading && currentFiltered.length > 0 && (
        <>
          <div style={{ display: 'flex', gap: 16, marginBottom: 24 }}>
            <div style={{ flex: 1, background: 'var(--surface-2)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius)', padding: '14px 16px', textAlign: 'center' }}>
              <p className="mono" style={{ fontSize: 9, color: 'var(--text-3)', letterSpacing: '0.1em', marginBottom: 6 }}>TOTAL</p>
              <p className="mono" style={{ fontSize: 16 }}>{fmtHMS(currentTotal)}</p>
            </div>
            <div style={{ flex: 1, background: 'var(--surface-2)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius)', padding: '14px 16px', textAlign: 'center' }}>
              <p className="mono" style={{ fontSize: 9, color: 'var(--text-3)', letterSpacing: '0.1em', marginBottom: 6 }}>vs 이전</p>
              <p className="mono" style={{ fontSize: 16, color: delta === null ? 'var(--text-3)' : delta >= 0 ? 'var(--running)' : 'var(--danger)' }}>
                {delta === null ? '—' : `${delta >= 0 ? '+' : ''}${delta}%`}
              </p>
            </div>
          </div>
          {currentFiltered.map((t) => (
            <TagBar key={t.tagId} summary={t} total={currentTotal} />
          ))}
        </>
      )}

      {showPicker && (
        <TagPickerModal
          tagTree={tagTree}
          currentTagId={selectedTagId}
          onSelect={(id) => { setSelectedTagId(id); setShowPicker(false) }}
          onClose={() => setShowPicker(false)}
        />
      )}
    </div>
  )
}

// ────────────────────────────────────────────────────────────
// Main
// ────────────────────────────────────────────────────────────

type TabKey = 'daily' | 'weekly' | 'monthly' | 'tag'

const TABS: { key: TabKey; label: string }[] = [
  { key: 'daily', label: '일별' },
  { key: 'weekly', label: '주별' },
  { key: 'monthly', label: '월별' },
  { key: 'tag', label: '태그별' },
]

export default function LogsView() {
  const memberId = useAuthStore((s) => s.memberId)
  const [activeTab, setActiveTab] = useState<TabKey>('daily')

  return (
    <AppShell>
      <div className="page">
        <div className="topbar">
          <span className="topbar-brand">timemgr</span>
        </div>

        <div style={{ padding: '24px 0' }}>
          <p className="mono" style={{ fontSize: 10, color: 'var(--accent)', letterSpacing: '0.2em', textTransform: 'uppercase', marginBottom: 20 }}>
            logs
          </p>

          {/* Tab bar */}
          <div style={{ display: 'flex', gap: 2, marginBottom: 28, background: 'var(--surface-2)', borderRadius: 'var(--radius)', padding: 3 }}>
            {TABS.map((t) => (
              <button
                key={t.key}
                onClick={() => setActiveTab(t.key)}
                className="mono"
                style={{ flex: 1, padding: '6px 0', background: activeTab === t.key ? 'var(--surface)' : 'transparent', border: 'none', borderRadius: 'calc(var(--radius) - 2px)', color: activeTab === t.key ? 'var(--text)' : 'var(--text-3)', fontSize: 11, cursor: 'pointer', transition: 'all 0.15s', boxShadow: activeTab === t.key ? 'var(--shadow-active)' : undefined }}
              >
                {t.label}
              </button>
            ))}
          </div>

          {memberId && activeTab === 'daily' && <DailyTab memberId={memberId} />}
          {memberId && activeTab === 'weekly' && <WeeklyTab memberId={memberId} />}
          {memberId && activeTab === 'monthly' && <MonthlyTab memberId={memberId} />}
          {memberId && activeTab === 'tag' && <TagTab memberId={memberId} />}
        </div>
      </div>
    </AppShell>
  )
}

// frontend/src/views/LogsView.vue
<template>
  <AppShell>
  <div class="page">
    <div class="topbar">
      <router-link :to="memberId ? `/members/${memberId}/today` : '/'" class="topbar-brand">timemgr</router-link>
    </div>

    <header class="log-header">
      <div>
        <p class="log-eyebrow mono">summary</p>
        <h1 class="log-title">Log</h1>
      </div>
    </header>

    <!-- Tabs -->
    <div class="tab-bar">
      <button
        v-for="tab in tabs"
        :key="tab.key"
        class="tab-btn"
        :class="{ 'tab-btn--active': activeTab === tab.key }"
        @click="switchTab(tab.key)"
      >{{ tab.label }}</button>
    </div>

    <!-- Date Navigator -->
    <div class="date-nav">
      <button class="nav-arrow" @click="shiftPeriod('prev')" title="이전">
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
          <path d="M9 11L5 7l4-4" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>

      <div class="date-display">
        <span class="date-label mono">{{ rangeLabel }}</span>
        <input
          v-if="activeTab === 'daily'"
          type="date"
          class="date-input"
          :value="dateInputValue"
          @change="onDateChange"
          title="날짜 선택"
        />
        <input
          v-else-if="activeTab === 'weekly'"
          type="week"
          class="date-input"
          :value="weekInputValue"
          @change="onWeekChange"
          title="주 선택"
        />
        <input
          v-else
          type="month"
          class="date-input"
          :value="monthInputValue"
          @change="onMonthChange"
          title="월 선택"
        />
      </div>

      <button class="nav-arrow" @click="shiftPeriod('next')" title="다음" :disabled="isToday">
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
          <path d="M5 3l4 4-4 4" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>
    </div>

    <!-- Loading -->
    <div v-if="loading" class="state-row">
      <span class="dot stopped"></span>
      <span class="mono">Loading…</span>
    </div>

    <!-- Error -->
    <div v-else-if="error" class="state-row error-state">
      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
        <circle cx="7" cy="7" r="6" stroke="currentColor" stroke-width="1.1"/>
        <path d="M7 4v4M7 9.5v.5" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
      </svg>
      <span>{{ error }}</span>
    </div>

    <!-- Empty -->
    <div v-else-if="!summary || summary.tagSummaries.length === 0" class="state-row">
      <span class="dot stopped"></span>
      <span class="mono">이 기간에 기록이 없습니다.</span>
    </div>

    <!-- Summary Content -->
    <div v-else class="summary-content">
      <!-- Total -->
      <div class="total-row">
        <span class="total-label mono">Total</span>
        <span class="total-value">{{ formatSeconds(summary.totalSeconds) }}</span>
      </div>

      <!-- Bar Chart -->
      <div class="chart-section">
        <div
          v-for="tag in summary.tagSummaries"
          :key="tag.tagId"
          class="chart-row"
        >
          <div class="chart-tag-name">
            <span class="tag-name-text">{{ tag.tagName }}</span>
            <span v-if="tag.parentTagName" class="tag-parent mono">{{ tag.parentTagName }}</span>
          </div>
          <div class="chart-bar-wrap">
            <div
              class="chart-bar"
              :style="{ width: barWidth(tag.totalSeconds) + '%' }"
            ></div>
          </div>
          <span class="chart-time mono">{{ formatSeconds(tag.totalSeconds) }}</span>
        </div>
      </div>

      <!-- Day Timeline -->
      <DayTimeline
        v-if="activeTab === 'daily'"
        :sessions="timelineSessions"
        :date="timelineDate"
      />

      <!-- Session List per Tag -->
      <div class="sessions-section">
        <div
          v-for="tag in summary.tagSummaries"
          :key="'sess-' + tag.tagId"
          class="tag-sessions"
        >
          <button class="tag-sessions-header" @click="toggleTag(tag.tagId)">
            <svg
              class="toggle-icon"
              :class="{ 'toggle-icon--open': openTags.has(tag.tagId) }"
              width="12" height="12" viewBox="0 0 12 12" fill="none"
            >
              <path d="M3 4.5L6 7.5L9 4.5" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <span class="tag-sessions-name">{{ tag.tagName }}</span>
            <span class="tag-sessions-count mono">{{ tag.sessionCount }}세션 · {{ formatSeconds(tag.totalSeconds) }}</span>
          </button>

          <div v-if="openTags.has(tag.tagId)" class="session-list">
            <div
              v-for="(session, idx) in tag.sessions"
              :key="idx"
              class="session-row"
            >
              <span class="session-time mono">{{ formatDateTime(session.startTime) }}</span>
              <span class="session-sep mono">–</span>
              <span class="session-time mono">{{ formatTimeOnly(session.endTime) }}</span>
              <span class="session-dur mono">{{ formatSeconds(session.durationSeconds) }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </AppShell>
</template>

<script setup>
import { ref, computed, watch, onMounted } from 'vue';
import { DateTime } from 'luxon';
import apiClient from '@/utils/apiClient';
import { getDailyRange, getWeeklyRange, getMonthlyRange, formatRangeLabel, shiftDate, formatSeconds } from '@/utils/dateRange.js';
import DayTimeline from '@/components/DayTimeline.vue';
import AppShell from '@/components/layout/AppShell.vue';

const tabs = [
  { key: 'daily', label: '일간' },
  { key: 'weekly', label: '주간' },
  { key: 'monthly', label: '월간' },
];

const activeTab = ref('daily');
const selectedDate = ref(new Date());
const summary = ref(null);
const loading = ref(false);
const error = ref(null);
const openTags = ref(new Set());

const auth = JSON.parse(localStorage.getItem('auth') || '{}');
const memberId = auth.memberId;

const rangeLabel = computed(() => formatRangeLabel(activeTab.value, selectedDate.value));

const dateInputValue = computed(() => DateTime.fromJSDate(selectedDate.value).toISODate());
const weekInputValue = computed(() => {
  const d = DateTime.fromJSDate(selectedDate.value);
  const week = d.weekNumber.toString().padStart(2, '0');
  return `${d.weekYear}-W${week}`;
});
const monthInputValue = computed(() => DateTime.fromJSDate(selectedDate.value).toFormat('yyyy-MM'));

const isToday = computed(() => {
  const today = DateTime.now().startOf('day');
  const sel = DateTime.fromJSDate(selectedDate.value).startOf('day');
  return sel >= today;
});

function getRange() {
  if (activeTab.value === 'daily') return getDailyRange(selectedDate.value);
  if (activeTab.value === 'weekly') return getWeeklyRange(selectedDate.value);
  return getMonthlyRange(selectedDate.value);
}

async function fetchSummary() {
  loading.value = true;
  error.value = null;
  summary.value = null;
  openTags.value = new Set();
  try {
    const { start, end } = getRange();
    const res = await apiClient.get('/api/v1/records/summary', { params: { startDate: start, endDate: end } });
    summary.value = res.data;
  } catch {
    error.value = '데이터를 불러오지 못했습니다.';
  } finally {
    loading.value = false;
  }
}

function switchTab(tab) {
  activeTab.value = tab;
}

function shiftPeriod(direction) {
  selectedDate.value = shiftDate(activeTab.value, selectedDate.value, direction);
}

function onDateChange(e) {
  if (e.target.value) selectedDate.value = new Date(e.target.value + 'T12:00:00');
}

function onWeekChange(e) {
  if (e.target.value) {
    const [year, week] = e.target.value.split('-W');
    selectedDate.value = DateTime.fromObject({ weekYear: parseInt(year), weekNumber: parseInt(week) }).toJSDate();
  }
}

function onMonthChange(e) {
  if (e.target.value) {
    const [year, month] = e.target.value.split('-');
    selectedDate.value = new Date(parseInt(year), parseInt(month) - 1, 1);
  }
}

function toggleTag(tagId) {
  const next = new Set(openTags.value);
  if (next.has(tagId)) next.delete(tagId);
  else next.add(tagId);
  openTags.value = next;
}

function barWidth(seconds) {
  if (!summary.value || summary.value.totalSeconds === 0) return 0;
  return Math.round((seconds / summary.value.totalSeconds) * 100);
}

function formatDateTime(iso) {
  return DateTime.fromISO(iso).toFormat('MM-dd HH:mm');
}

function formatTimeOnly(iso) {
  return DateTime.fromISO(iso).toFormat('HH:mm');
}

const timelineSessions = computed(() => {
  if (!summary.value || activeTab.value !== 'daily') return [];
  return summary.value.tagSummaries.flatMap((tag, tagIndex) =>
    tag.sessions.map(s => ({
      tagId: tag.tagId,
      tagName: tag.tagName,
      tagIndex,
      startTime: s.startTime,
      endTime: s.endTime,
      durationSeconds: s.durationSeconds,
    }))
  );
});

const timelineDate = computed(() =>
  DateTime.fromJSDate(selectedDate.value).startOf('day')
);

watch([activeTab, selectedDate], fetchSummary);
onMounted(fetchSummary);
</script>

<style scoped>
.topbar-actions {
  display: flex;
  align-items: center;
  gap: 12px;
}

.log-header {
  padding: 52px 0 28px;
  border-bottom: 1px solid var(--border-subtle);
}

.log-eyebrow {
  font-size: 10px;
  color: var(--text-2);
  letter-spacing: 0.18em;
  text-transform: uppercase;
  margin-bottom: 10px;
}

.log-title {
  font-family: var(--font-serif);
  font-size: 34px;
  color: var(--text);
  font-weight: 400;
}

/* Tabs */
.tab-bar {
  display: flex;
  gap: 2px;
  padding: 16px 0 0;
  border-bottom: 1px solid var(--border-subtle);
}

.tab-btn {
  font-family: var(--font-mono);
  font-size: 11px;
  letter-spacing: 0.1em;
  color: var(--text-3);
  background: transparent;
  padding: 8px 14px;
  border-radius: var(--radius) var(--radius) 0 0;
  border: 1px solid transparent;
  border-bottom: none;
  transition: color var(--t), background var(--t), border-color var(--t);
  text-transform: uppercase;
}

.tab-btn:hover { color: var(--text-2); }

.tab-btn--active {
  color: var(--text);
  background: var(--surface);
  border-color: var(--border-subtle);
  border-bottom-color: var(--surface);
  margin-bottom: -1px;
}

/* Date Navigator */
.date-nav {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 0;
  border-bottom: 1px solid var(--border-subtle);
}

.nav-arrow {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  background: transparent;
  color: var(--text-2);
  border-radius: var(--radius);
  transition: color var(--t), background var(--t);
}

.nav-arrow:hover:not(:disabled) {
  color: var(--text);
  background: var(--surface);
}

.nav-arrow:disabled { opacity: 0.25; cursor: default; }

.date-display {
  display: flex;
  align-items: center;
  gap: 10px;
  position: relative;
}

.date-label {
  font-size: 13px;
  color: var(--text);
}

.date-input {
  position: absolute;
  inset: 0;
  opacity: 0;
  cursor: pointer;
  width: 100%;
  height: 100%;
}

/* States */
.state-row {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 56px 0;
  color: var(--text-2);
  font-size: 13px;
}
.error-state { color: var(--danger); }
.dot { width: 6px; height: 6px; border-radius: 50%; background: var(--text-3); }

/* Summary */
.summary-content { padding-top: 0; }

.total-row {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  padding: 20px 0;
  border-bottom: 1px solid var(--border-subtle);
}

.total-label {
  font-size: 10px;
  color: var(--text-3);
  letter-spacing: 0.18em;
  text-transform: uppercase;
}

.total-value {
  font-family: var(--font-serif);
  font-size: 28px;
  color: var(--text);
}

/* Bar Chart */
.chart-section {
  padding: 20px 0;
  border-bottom: 1px solid var(--border-subtle);
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.chart-row {
  display: grid;
  grid-template-columns: 140px 1fr 80px;
  gap: 12px;
  align-items: center;
}

.chart-tag-name {
  display: flex;
  flex-direction: column;
  gap: 2px;
  min-width: 0;
}

.tag-name-text {
  font-size: 13px;
  color: var(--text);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.tag-parent {
  font-size: 10px;
  color: var(--text-3);
  letter-spacing: 0.06em;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.chart-bar-wrap {
  background: var(--surface-2);
  border-radius: var(--radius);
  height: 4px;
  overflow: hidden;
}

.chart-bar {
  height: 100%;
  background: var(--accent);
  border-radius: var(--radius);
  transition: width 400ms ease;
}

.chart-time {
  font-size: 12px;
  color: var(--text-2);
  text-align: right;
}

/* Sessions */
.sessions-section {
  padding-top: 8px;
}

.tag-sessions {
  border-bottom: 1px solid var(--border-subtle);
}

.tag-sessions-header {
  display: flex;
  align-items: center;
  gap: 10px;
  width: 100%;
  background: transparent;
  color: var(--text);
  padding: 14px 0;
  transition: color var(--t);
  text-align: left;
}

.tag-sessions-header:hover { color: var(--accent); }

.toggle-icon {
  flex-shrink: 0;
  color: var(--text-3);
  transition: transform var(--t);
}

.toggle-icon--open { transform: rotate(0deg); }
.toggle-icon:not(.toggle-icon--open) { transform: rotate(-90deg); }

.tag-sessions-name {
  font-size: 13px;
  flex: 1;
}

.tag-sessions-count {
  font-size: 11px;
  color: var(--text-3);
  letter-spacing: 0.06em;
  flex-shrink: 0;
}

.session-list {
  padding-bottom: 8px;
}

.session-row {
  display: grid;
  grid-template-columns: auto auto auto 1fr;
  gap: 8px;
  align-items: center;
  padding: 8px 0 8px 22px;
  border-top: 1px solid var(--border-subtle);
}

.session-time {
  font-size: 12px;
  color: var(--text-2);
}

.session-sep {
  font-size: 12px;
  color: var(--text-3);
}

.session-dur {
  font-size: 12px;
  color: var(--text-3);
  text-align: right;
}

.mono { font-family: var(--font-mono); }

@media (max-width: 768px) {
  .log-header { padding: 36px 0 24px; }
  .log-title { font-size: 28px; }

  .chart-row {
    grid-template-columns: 100px 1fr 70px;
    gap: 8px;
  }

  .session-row {
    padding-left: 12px;
  }
}

@media (max-width: 480px) {
  .log-title { font-size: 24px; }

  .chart-row {
    grid-template-columns: 80px 1fr 60px;
    gap: 6px;
  }

  .total-value { font-size: 22px; }
}
</style>
