// frontend/src/views/OAuthCallbackView.tsx
'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/hooks/useAuth'

export default function OAuthCallbackView() {
  const router = useRouter()
  const { googleLogin } = useAuth()
  const [error, setError] = useState('')

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const code = params.get('code')
    const oauthError = params.get('error')

    if (oauthError || !code) {
      router.replace('/login')
      return
    }

    const redirectUri = `${window.location.origin}/oauth/callback`
    googleLogin(code, redirectUri).catch((e: unknown) => {
      const msg = (e as { response?: { data?: { message?: string } } })?.response?.data?.message
      setError(msg || 'Google 로그인에 실패했습니다. 다시 시도해주세요.')
    })
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  if (error) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh' }}>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 20, textAlign: 'center' }}>
          <p className="mono" style={{ fontSize: 11, color: 'var(--danger)' }}>{error}</p>
          <Link href="/login" className="btn btn-primary">
            Back to Login
            <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
              <path d="M2.5 6.5h8M7 3l3.5 3.5L7 10" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh' }}>
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
        <div className="spinner" />
        <p className="mono" style={{ fontSize: 11, letterSpacing: '0.1em', color: 'var(--text-2)', textTransform: 'uppercase' }}>
          Signing in...
        </p>
      </div>
    </div>
  )
}

// frontend/src/views/OAuthCallbackView.vue
<template>
  <div class="callback-page">
    <div v-if="error" class="callback-error">
      <p class="error-msg">{{ error }}</p>
      <router-link to="/login" class="btn btn-primary">
        Back to Login
        <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
          <path d="M2.5 6.5h8M7 3l3.5 3.5L7 10" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </router-link>
    </div>
    <div v-else class="callback-loading">
      <div class="spinner" />
      <p class="loading-msg">Signing in...</p>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useAuth } from '@/composables/useAuth';

const router = useRouter();
const { googleLogin } = useAuth();
const error = ref('');

onMounted(async () => {
  const params = new URLSearchParams(window.location.search);
  const code = params.get('code');
  const oauthError = params.get('error');

  if (oauthError || !code) {
    await router.replace('/login');
    return;
  }

  const redirectUri = `${window.location.origin}/oauth/callback`;
  try {
    await googleLogin(code, redirectUri);
  } catch (e) {
    error.value = e.response?.data?.message || 'Google 로그인에 실패했습니다. 다시 시도해주세요.';
  }
});
</script>

<style scoped>
.callback-page {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
}

.callback-loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
}

.spinner {
  width: 32px;
  height: 32px;
  border: 2px solid var(--border, #e5e7eb);
  border-top-color: var(--accent);
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.loading-msg {
  font-family: var(--font-mono);
  font-size: 11px;
  letter-spacing: 0.1em;
  color: var(--text-2);
  text-transform: uppercase;
}

.callback-error {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 20px;
  text-align: center;
}

.error-msg {
  font-size: 13px;
  color: var(--danger);
  font-family: var(--font-mono);
}
</style>
