// frontend/src/views/RegisterView.tsx
'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useAuth } from '@/hooks/useAuth'

export default function RegisterView() {
  const { register } = useAuth()
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  async function handleRegister(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    setError('')
    try {
      await register(name, email, password)
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message
      setError(msg || '회원가입에 실패했습니다. 다시 시도해주세요.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="page auth-page">
      <div className="topbar">
        <span className="topbar-brand">timemgr</span>
      </div>

      <div className="auth-body">
        <div>
          <p className="auth-eyebrow">create account</p>
          <h1 className="auth-title">Get<br />started.</h1>
        </div>

        <form className="auth-form" onSubmit={handleRegister}>
          <div className="field">
            <label>Name</label>
            <input
              type="text"
              autoComplete="name"
              placeholder="Your name"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
          </div>
          <div className="field">
            <label>Email</label>
            <input
              type="email"
              autoComplete="email"
              placeholder="you@example.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          <div className="field">
            <label>Password</label>
            <input
              type="password"
              autoComplete="new-password"
              placeholder="••••••••"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          {error && <p className="auth-error">{error}</p>}
          <button className="btn btn-primary" type="submit" disabled={loading} style={{ width: '100%', justifyContent: 'center' }}>
            {loading ? '...' : (
              <>
                Create account
                <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                  <path d="M2.5 6.5h8M7 3l3.5 3.5L7 10" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              </>
            )}
          </button>
        </form>

        <p className="auth-switch">
          Already have an account?{' '}
          <Link href="/login" className="auth-link">Sign in</Link>
        </p>
      </div>
    </div>
  )
}

// frontend/src/views/RegisterView.vue
<template>
  <div class="page auth-page">
    <div class="topbar">
      <span class="topbar-brand">timemgr</span>
    </div>

    <div class="auth-body">
      <div class="auth-hero">
        <p class="auth-eyebrow">create account</p>
        <h1 class="auth-title">Get<br>started.</h1>
      </div>

      <form class="auth-form" @submit.prevent="handleRegister">
        <div class="field">
          <label>Name</label>
          <input v-model="name" type="text" autocomplete="name" placeholder="Your name" />
        </div>

        <div class="field">
          <label>Email</label>
          <input v-model="email" type="email" autocomplete="email" placeholder="you@example.com" />
        </div>

        <div class="field">
          <label>Password</label>
          <input v-model="password" type="password" autocomplete="new-password" placeholder="••••••••" />
        </div>

        <p v-if="error" class="auth-error">{{ error }}</p>

        <button class="btn btn-primary" type="submit" :disabled="loading">
          <span v-if="loading">...</span>
          <span v-else>Create account</span>
          <svg v-if="!loading" width="13" height="13" viewBox="0 0 13 13" fill="none">
            <path d="M2.5 6.5h8M7 3l3.5 3.5L7 10" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </button>
      </form>

      <p class="auth-switch">
        Already have an account?
        <router-link to="/login" class="auth-link">Sign in</router-link>
      </p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useAuth } from '@/composables/useAuth';

const { register } = useAuth();

const name = ref('');
const email = ref('');
const password = ref('');
const error = ref('');
const loading = ref(false);

async function handleRegister() {
  error.value = '';
  loading.value = true;
  try {
    await register(name.value, email.value, password.value);
  } catch (e) {
    error.value = e.response?.data?.message || '회원가입에 실패했습니다';
  } finally {
    loading.value = false;
  }
}
</script>

<style scoped>
.auth-page { position: relative; }

.auth-body {
  display: flex;
  flex-direction: column;
  justify-content: center;
  min-height: calc(100vh - 52px);
  max-width: 320px;
  padding-bottom: 60px;
}

.auth-hero { margin-bottom: 48px; }

.auth-eyebrow {
  font-family: var(--font-mono);
  font-size: 10px;
  color: var(--accent);
  letter-spacing: 0.2em;
  text-transform: uppercase;
  margin-bottom: 16px;
  display: flex;
  align-items: center;
  gap: 10px;
}

.auth-eyebrow::before {
  content: '';
  display: inline-block;
  width: 24px;
  height: 1px;
  background: var(--accent);
  opacity: 0.5;
}

.auth-title {
  font-family: var(--font-serif);
  font-size: clamp(36px, 6vw, 56px);
  line-height: 1.08;
  color: var(--text);
  letter-spacing: -0.01em;
}

.auth-form {
  display: flex;
  flex-direction: column;
  gap: 28px;
  margin-bottom: 32px;
}

.auth-error {
  font-size: 12px;
  color: var(--danger);
  font-family: var(--font-mono);
}

.auth-switch {
  font-size: 12px;
  color: var(--text-2);
}

.auth-link {
  color: var(--accent);
  transition: opacity var(--t);
}
.auth-link:hover { opacity: 0.7; }
</style>
